# Generated by Django 5.1.6 on 2025-09-30 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('view_question', 'View Questions'), ('add_question', 'Add Questions'), ('input_suggestion', 'Input Suggestion'), ('generate_image', 'Generate Image'), ('lecture_notes', 'Lecture Notes'), ('questcurator', 'QuestCurator'), ('database_view', 'Database View'), ('notes_ai', 'Notes AI')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
