# Generated by Django 5.1.6 on 2025-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_featurepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurepermission',
            options={'verbose_name': 'Feature Permission', 'verbose_name_plural': 'Feature Permissions'},
        ),
        migrations.AlterField(
            model_name='featurepermission',
            name='feature',
            field=models.CharField(choices=[('view_question', 'View Questions'), ('add_question', 'Add Questions'), ('add_input_suggestion', 'Add Input Suggestion'), ('view_input_suggestion', 'View Input Suggestion'), ('add_lecture_notes', 'Add Lecture Notes'), ('view_lecture_notes', 'View Lecture Notes'), ('generate_image', 'Generate Image'), ('questcurator', 'QuestCurator'), ('database_view', 'Database View'), ('notes_ai', 'Notes AI')], max_length=50),
        ),
    ]
